# Multi-database mapping example
# This example shows how to map data from multiple separate databases
#
# IMPORTANT: Column Naming After JOINs
# When JOINs are performed, columns are automatically prefixed with database aliases
# to prevent name collisions (e.g., "id" becomes "hr_id", "pm_id").
# In your field mappings, use the original column names - the system will automatically
# resolve them to the correct prefixed columns.

databases:
  - path: "data/hr_system.db"
    alias: "hr"
  - path: "data/project_management.db"
    alias: "pm"
  - path: "data/time_tracking.db"
    alias: "time"

mappings:
  - name: "employee_projects"
    
    # Complex JOIN across multiple databases
    joins:
      - type: "INNER"
        left_table: "hr.employees"
        right_table: "pm.project_assignments"
        condition: "employees.employee_id = project_assignments.employee_id"
      - type: "INNER"
        left_table: "pm.project_assignments"
        right_table: "pm.projects"
        condition: "project_assignments.project_id = projects.project_id"
      - type: "LEFT"
        left_table: "pm.project_assignments"
        right_table: "time.time_entries"
        condition: "project_assignments.assignment_id = time_entries.assignment_id"
    
    nodes:
      - label: "Employee"
        source: "employees"
        id_field: "employee_id"
        properties:
          - field: "first_name"
            type: "string"
          - field: "last_name"
            type: "string"
          - field: "email"
            type: "string"
          - field: "department"
            type: "string"
          - field: "hire_date"
            type: "date"
          - field: "salary"
            type: "float"
        computed_properties:
          - name: "full_name"
            type: "string"
            expression: "CONCAT(first_name, ' ', last_name)"
          - name: "years_employed"
            type: "integer"
            expression: "YEAR(CURRENT_DATE) - YEAR(hire_date)"
      
      - label: "Project"
        source: "projects"
        id_field: "project_id"
        properties:
          - field: "project_name"
            type: "string"
          - field: "description"
            type: "string"
          - field: "start_date"
            type: "date"
          - field: "end_date"
            type: "date"
          - field: "budget"
            type: "float"
          - field: "status"
            type: "string"
      
      - label: "Department"
        source: "employees"
        id_field: "department"
        properties:
          - field: "department"
            type: "string"
    
    relationships:
      - type: "ASSIGNED_TO"
        source: "pm.project_assignments"
        from_id_column: "employee_id"
        to_id_column: "project_id"
        from_node: "Employee"
        to_node: "Project"
        properties:
          - field: "assignment_date"
            type: "date"
          - field: "role"
            type: "string"
          - field: "allocation_percentage"
            type: "float"
      
      - type: "WORKS_IN"
        source: "hr.employees"
        from_id_column: "employee_id"
        to_id_column: "department_id"
        from_node: "Employee"
        to_node: "Department"
      
      - type: "LOGGED_TIME"
        source: "pm.time_entries"
        from_id_column: "employee_id"
        to_id_column: "project_id"
        from_node: "Employee"
        to_node: "Project"
        properties:
          - field: "hours_logged"
            type: "float"
          - field: "entry_date"
            type: "date"
          - field: "task_description"
            type: "string"

  # Separate mapping for organizational structure
  - name: "org_structure"
    
    relationships:
      - type: "REPORTS_TO"
        source: "hr.employees"          # Explicit source table
        from_id_column: "employee_id"   # Subordinate's ID
        to_id_column: "manager_id"      # Manager's ID
        from_node: "Employee"           # References employees from employee_project mapping
        to_node: "Employee"             # Also references employees (as managers)
        properties:
          - field: "reporting_start_date"
            type: "date"

output:
  format: "csv"
  directory: "output/multi_database"